branding:
  icon: "check-circle"
  color: "blue"

name: 'Submodule Hash'
description: 'Generates a hash based on the submodule commit(s) for use in caching workflows.'
inputs:
  path:
    description: 'Path to the submodule'
    required: true
    default: './'
outputs:
  sha256:
    description: "Submodule's commit hash"
    value: ${{ steps.submodule-version-hash.outputs.sha256 }}
runs:
  using: "composite"
  steps:
    - name: Submodule Hash
      id: submodule-version-hash
      shell: bash
      run: |
        ${GITHUB_ACTION_PATH}/hash.sh ${{ inputs.path }}
        echo "sha256=$(${GITHUB_ACTION_PATH}/hash.sh ${{ inputs.path }})" >> $GITHUB_OUTPUT
